# Generated by Django 5.1.2 on 2024-10-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_name', models.CharField(choices=[('Cessna C525 Citation', 'Cessna C525 Citation'), ('Embraer Phenom 300E', 'Embraer Phenom 300E'), ('A320', 'A320'), ('A380', 'A380'), ('Gulfstream G300', 'Gulfstream G300'), ('Bombardier Global 7500', 'Bombardier Global 7500')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('airport', models.CharField(choices=[('JFK', 'John F. Kennedy International Airport'), ('LAX', 'Los Angeles International Airport'), ('ATL', 'Atlanta Hartsfield-Jackson International Airport')], max_length=50)),
                ('booking_time', models.IntegerField(choices=[(4, '4 hour'), (8, '8 hours'), (16, '16 hours')])),
                ('price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
            ],
        ),
    ]
