# Generated by Django 5.1.2 on 2024-10-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_flight',
            name='plane_name',
            field=models.CharField(choices=[('light1', 'Cessna C525 Citation'), ('light2', 'Embraer Phenom 300E'), ('airline1', 'A380'), ('airline2', 'A320'), ('heavy1', 'Gulfstream G300'), ('heavy2', 'Bombardier Global 7500')], max_length=50),
        ),
    ]
