# Generated by Django 5.1.2 on 2024-10-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_booking_flight_plane_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_flight',
            name='booking_time',
            field=models.CharField(choices=[('4h', '4 hour'), ('8h', '8 hours'), ('16h', '16 hours')], max_length=50),
        ),
    ]
