# Generated by Django 5.1.2 on 2024-10-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_booking_flight_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_flight',
            name='price',
        ),
        migrations.AlterField(
            model_name='booking_flight',
            name='booking_time',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4),
        ),
    ]
