# Generated by Django 5.1.2 on 2024-10-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_remove_booking_flight_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_flight',
            name='plane_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='booking_flight',
            name='booking_time',
            field=models.CharField(max_length=50),
        ),
    ]
