# Generated by Django 5.1.2 on 2024-10-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_booking_flight_plane_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_flight',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
