# Generated by Django 5.1.2 on 2024-10-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_alter_booking_flight_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_flight',
            old_name='price',
            new_name='total_price',
        ),
    ]
