# Generated by Django 5.1.2 on 2024-10-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_rename_price_booking_flight_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_flight',
            name='plane_image',
            field=models.ImageField(blank=True, upload_to='Images'),
        ),
    ]
