# Generated by Django 5.1.2 on 2024-10-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_alter_booking_flight_plane_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_flight',
            name='plane_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
