# Generated by Django 5.1.2 on 2024-10-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_alter_booking_flight_plane_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_flight',
            name='email',
        ),
        migrations.AddField(
            model_name='booking_flight',
            name='phone',
            field=models.CharField(default='None', max_length=15),
        ),
    ]
